<?php use dawfony\Ti;?>
<?php Ti::extend("view/MainView.phtml")?>
<?php Ti::startBlock("estilo")?>
<script>var URL_PATH = "<?=$URL_PATH?>"</script>
<script src="like.js"></script>
#icono{
	margin-left:90%;
}
.cuadradro{
	border:1px solid black;
	border-radius: 10px;
	margin-top:10px;
}
.nuevopost {
	position:fixed;
	bottom : 50px;
	right : 50px;
	z-index : 1;
}
<?php Ti::endBlock()?>
<?php Ti::startBlock("contenido")?>
<?php global $URL_PATH;?>
<?php foreach ($listado as $valor) {?>
<div class="container-fluid cuadradro">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-3">
                    <img class="img-fluid" src="<?=$URL_PATH?>/assets/img/<?=$valor->foto?>">
				</div>
				<div class="col-md-6">
					<h4><?=$valor->resumen?></h4>
					<p><?=$valor->texto?></p>
					<?php if($_SESSION["login"]){ ?>
						<a href="#" class="boton" id="<?=$valor->id?>"><i class="fa fa-heart"></i><span></span></a>
						<a href="<?=$URL_PATH?>/masinformacion/<?=$valor->id?>"><i class="fa fa-comments"></i><span></span></a><?= $valor->num_comentarios ?>
					<?php }?>
					<a class="btn btn-primary"role="button" href="<?=$URL_PATH?>/masinformacion/<?=$valor->id?>">Leer mas</a> 
				</div>
				<div class="col-md-3">
					<?php if(($_SESSION["login"] ?? " ") == $valor->usuario_login){ ?>
					<p>Por:<?=$valor->usuario_login?></p>
					<?php }else { ?>
					<p>Por:<a href="<?=$URL_PATH?>/informacionpersonalalguien/<?=$valor->usuario_login?>"><?=$valor->usuario_login?></a></p>
					<?php } ?>
					<p><?=$valor->fecha?></p>
                   <p><?=$valor->descripcion?></p> 
				</div>
            </div>
		</div>
	</div>
</div>
<?php }?>
        <?php if(isset($_SESSION['login'])) { ?>
<div><h1 id="icono"><a class="nuevopost" href="<?=$URL_PATH?>/anadir">+</a></h1></div>
	<?php	}?>
<?php Ti::endBlock()?>
<?php Ti::endExtend()?>