<?php use dawfony\Ti;?>
<?php Ti::extend("view/MainView.phtml")?>
<?php Ti::startBlock("cabecera")?>
<?php Ti::endBlock()?>
<?php Ti::startBlock("estilo")?>
#icono{
	margin-left:90%;
}
.cuadradro{
	border:1px solid black;
	border-radius: 10px;
	margin-top:10px;
}
.nuevopost {
	position:fixed;
	bottom : 50px;
	right : 50px;
	z-index : 1;
}
<?php Ti::endBlock()?>
<?php Ti::startBlock("contenido")?>
<?php global $URL_PATH;?>
<?php foreach ($listado as $valor) {?>
<div class="container-fluid cuadradro">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-3">
                    <img class="img-fluid" src="<?=$URL_PATH?>/assets/img/<?=$valor->foto?>">
				</div>
				<div class="col-md-6">
					<h4><?=$valor->resumen?></h4>
					<p><?=$valor->texto?></p>
					<?php if(isset($_SESSION["login"])){ ?>
						<a href="javascript:void(0)" onclick="evento(<?= $valor->id ?>)"><i id="<?=$valor->id?>" 
						<?php if($valor->like) { ?>
							class="fa fa-heart text-danger"
						<?php }else { ?>
							class="fa fa-heart"
							<?php }?>></i></a>
						<span id="numerolike<?= $valor->id ?>"><?= $valor->num_like?></span>
						<a href="<?=$URL_PATH?>/masinformacion/<?=$valor->id?>"><i class="fa fa-comments"></i></a><?= $valor->num_comentarios ?>
					<?php }?>
					<a class="btn btn-primary"role="button" href="<?=$URL_PATH?>/masinformacion/<?=$valor->id?>">Leer mas</a> 
				</div>
				<div class="col-md-3">
					<?php if(($_SESSION["login"] ?? " ") == $valor->usuario_login){ ?>
					<p>Por:<?=$valor->usuario_login?></p>
					<?php }else { ?>
					<p>Por:<a href="<?=$URL_PATH?>/informacionpersonalalguien/<?=$valor->usuario_login?>"><?=$valor->usuario_login?></a></p>
					<?php } ?>
					<p><?=$valor->fecha?></p>
                   <p><?=$valor->categoria?></p> 
				</div>
            </div>
		</div>
	</div>
</div>
<?php }?>
<nav aria-label="Page navigation" class="mt-2">
    <ul class="pagination justify-content-end">
        <li class="page-item<?=($pagina - 1 < 1 ? " disabled":"")?>">
            <a class="page-link" href="<?=$URL_PATH?>/seguidores/pagina/<?=($pagina - 1)?>" tabindex="-1">Anterior</a>
        </li>
        <li class="page-item disabled">
        <a class="page-link" href="#"><?=$pagina?></a>
    </li>
        <li class="page-item<?=($pagina + 1 > $numpaginas ? " disabled":"")?>" >
            <a class="page-link" href="<?=$URL_PATH?>/seguidores/pagina/<?=($pagina + 1)?>">Siguiente</a>
        </li>
    </ul>
</nav>
        <?php if(isset($_SESSION['login'])) { ?>
<div><h1 id="icono"><a class="nuevopost" href="<?=$URL_PATH?>/anadir">+</a></h1></div>
	<?php	}?>
	<script src="<?= $URL_PATH ?>/js/like.js"></script>
<?php Ti::endBlock()?>
<?php Ti::endExtend()?>