<?php use dawfony\Ti;?>
<?php Ti::extend("view/MainView.phtml")?>
<?php Ti::startBlock("contenido")?>
<?php global $URL_PATH;?>
<?php if($error != "") { ?>
<span class="alert alert-danger" role="alert"><?=$error?></span> <br><br>
<?php } ?>
<form method="post" action="<?=$URL_PATH?>/login">
  <div class="form-group">
    <label for="login">Login</label>
    <input type="login" class="form-control" id="login" name="login" value ="<?=$login ?? ""?>">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" value="<?=$password ?? ""?>">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<?php Ti::endBlock()?>
<?php Ti::endExtend()?>