<?php use dawfony\Ti;?>
<?php global $URL_PATH;?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="<?= $URL_PATH ?>/js/main.js"></script>
    <script>var URL_PATH = "<?= $URL_PATH ?>" // Pasamos el URL_PATH de php a Javascript.
    </script>
    <?php Ti::startBlock("title")?>
        <title><?=$title?></title>
    <?php Ti::endBlock()?>
    <style>
      body{
        margin-right: 10%;
        margin-left: 10%;
      }
      #borrar{
        margin-left: 10px;
        margin-right: 10px;
      }
      .margenes {
        border-radius: 2px;
        margin-top: 10px;
      }
      img {
        max-height: 150px;
        max-width: 150px;
      }
      <?php Ti::startBlock("estilo");?>
      <?php Ti::endBlock();?>
    </style>
</head>
<body>
    <div class="jumbotron">
        <h1 class="display-4">Social DAW</h1>
        <p class="lead">Tu red social de anime, Kpop y jpop</p>
        <hr class="my-4">
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info sticky-top myfont">
    <a class="navbar-brand" href="<?= $URL_PATH ?>/">Lo último</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <?php 
         if(isset($_SESSION['login'])) { ?>
           <li class="nav-item">
             <a class="nav-link" href="<?=$URL_PATH?>/perfil">Mi perfil <span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="<?=$URL_PATH?>/seguidores">Mis seguidores <span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item">
           <a href="javascript:void(0)" onclick="cerrarsesion()" id ="borrar" class="btn btn-primary" role="button">Cerrar session</a>
           </li> 
        <?php }else { ?>

      <li class="nav-item">
        <a class="nav-link" href="<?=$URL_PATH?>/registro">Registrate <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?=$URL_PATH?>/login">Login <span class="sr-only">(current)</span></a>
      </li>
      <?php }
    ?>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Enviar</button>
    </form>
  </div>
  </nav>
  <?php Ti::startBlock("contenido")?>
  <?php Ti::endBlock()?>
  <footer class="footer bg-primary text-white margenes">Creado por Sandra</footer>
</body>
</html>