<?php use dawfony\Ti;?>
<?php global $URL_PATH;?>
<script src="<?= $URL_PATH ?>/js/comprobar.js"></script>
<script src="<?= $URL_PATH ?>/js/comprobarnombre.js"></script>
<?php Ti::extend("view/MainView.phtml")?>
<?php Ti::startBlock("contenido")?>
<p style="color:red" id="error"><?=$error ?? ""?></p>
<form method="post" action="<?=$URL_PATH?>/registro" onsubmit="return comprobar()">
  <div class="form-group">
    <label for="login">Login</label>
    <input type="text" class="form-control" onchange="comprobarnombre()" id="login" name="login" value ="<?=$login ?? ""?>">
  </div>
  
  <div class="form-group">
    <label for="password">Contraseña</label>
    <input type="password" class="form-control" id="password" name="password" value="<?=$password ?? ""?>">
  </div>
  <div class="form-group">
    <label for="passwordos">Repetir contraseña</label>
    <input type="password" class="form-control" id="passwordos" name="passwordos" value="<?=$passwordos ?? ""?>">
  </div>
  <div class="form-group">
    <label for="nombre">Tu nombre</label>
    <input type="text" class="form-control" id="nombre" name="nombre" value ="<?=$nombre ?? ""?>">
  </div>
  <div class="form-group">
    <label for="email">email</label>
    <input type="text" class="form-control" id="email" name="email" value ="<?=$email ?? ""?>">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<?php Ti::endBlock()?>
<?php Ti::endExtend()?>