<?php use dawfony\Ti;?>
<?php Ti::extend("view/MainView.phtml")?>
<?php Ti::startBlock("contenido")?>
<?php global $URL_PATH;?>
<p style="color:red"><?=$error ?? ""?></p>
<form method="post" action="<?=$URL_PATH?>/registro">
  <div class="form-group">
    <label for="login">Login</label>
    <input type="login" class="form-control" id="login" name="login" value ="<?=$login ?? ""?>">
  </div>
  
  <div class="form-group">
    <label for="exampleInputPassword1">Contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" value="<?=$password ?? ""?>">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Repetir contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword2" name="passwordos" value="<?=$passwordos ?? ""?>">
  </div>
  <div class="form-group">
    <label for="login">Tu nombre</label>
    <input type="login" class="form-control" id="login" name="nombre" value ="<?=$nombre ?? ""?>">
  </div>
  <div class="form-group">
    <label for="login">email</label>
    <input type="login" class="form-control" id="login" name="email" value ="<?=$email ?? ""?>">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<?php Ti::endBlock()?>
<?php Ti::endExtend()?>